language: ruby
rvm:
  - 1.9.3
  - 1.9.2
  - ruby-head
  # They fail for some known issues:
  # - `Open3.popen` in jruby
  # - named group captures in rbx
  - jruby-19mode
  - rbx-19mode
before_script:
  - sudo apt-get install graphviz
script: rake
